version: '3.3'
services:
    odoo:
        container_name: odoo15
        image: pimiya/odoo:latest
        networks:
            - default
        ports:
            - "0.0.0.0:8069:8069"
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
volumes:
    odoo-web-data: